name: portal
services:
  portal-db:
    container_name: portal-db
    environment:
      MYSQL_DATABASE: oficial_intranet
      MYSQL_PASSWORD: Comt3c0
      MYSQL_ROOT_PASSWORD: .root.
      MYSQL_USER: ecuevas
    image: mysql
    networks:
      network-id: null
    ports:
    - mode: ingress
      target: 3306
      published: "3306"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/roger/Desarrollo/docker/portal/db
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
  portal-php:
    build:
      context: /home/roger/Desarrollo/docker/portal
      dockerfile: Dockerfile
      args:
        php_version: 7.4-apache
    container_name: portal-php
    depends_on:
      portal-db:
        condition: service_started
        restart: true
        required: true
    environment:
      MYSQL_DATABASE: oficial_intranet
      MYSQL_HOST: portal-db
      MYSQL_PASSWORD: Comt3c0
      MYSQL_ROOT_PASSWORD: .root.
      MYSQL_USER: ecuevas
      MYSQL_VERSION: "5.7"
      PHP_PORT: "80"
      PHP_VERSION: 7.4-apache
    links:
    - portal-db
    networks:
      network-id: null
    ports:
    - mode: ingress
      target: 80
      published: "80"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/roger/Desarrollo/docker/portal
      target: /var/www/html
      bind:
        create_host_path: true
networks:
  network-id:
    name: portal-network
